// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
 
// import NavbarHeader from "./components/NavbarHeader";
// import FooterComponent from "./components/FooterComponent";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
        
//         <NavbarHeader/>
//         {children}
//         <FooterComponent/>
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import localFont from "next/font/local";
import { CartProvider } from "use-shopping-cart";
import "./globals.css";

import NavbarHeader from "./components/NavbarHeader";
import FooterComponent from "./components/FooterComponent";
import CartProviderWrapper from "@/components/cardProviderWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <CartProviderWrapper>
          <NavbarHeader />
          {children}
          <FooterComponent />
          </CartProviderWrapper>
      </body>
    </html>
  );
}
