 
 

import type { Metadata } from "next";
import localFont from "next/font/local";
 
import "./globals.css";

import NavbarHeader from "./components/NavbarHeader";
import FooterComponent from "./components/FooterComponent";
import CartProviderWrapper from "@/components/cardProviderWrapper";
 
import ClerkWrapper from "./components/Provider";
import ToastProvider from "@/components/toastProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "E-commerce Website ",
  description: "Generated by next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return ( 



    <html lang="en">


      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >  
        <ClerkWrapper>
         <CartProviderWrapper> 
          
          <NavbarHeader />
          <ToastProvider />
          {children}
          <FooterComponent />
          </CartProviderWrapper>
          
          </ClerkWrapper>
      </body>
    </html>
  );
}
